### ISSUE TITLE
[analysis] identify reasons of Medicare entitlement for ALS patients

### ISSUE THREAD

**Issue by sxinger** [gpcnetwork/cdc_als4m_mu#3]
For current Medicare-based ALS cohort, we want to investigate what are their reasons of Medicare entitlement to distinguish between the cases of late-onset (onset >= 65yo) and disabled early-onset (they are Medicare eligible because of ALS). 

We can use the deid source Medicare tables to identify that: 

| Schema | View | Column | Notes |
| -------   | ------ | -------- | ------- |
| MEDICARE_DEID_11_13| V_MBSF_AB_SUMMARY_DEID | COVSTART, BENE_DOB | you can calculate age at COVSTART to see if it was under 65 yo |
| MEDICARE_DEID_11_13| V_MBSF_AB_SUMMARY_DEID | OREC | https://resdac.org/cms-data/variables/original-reason-entitlement-code |
| MEDICARE_DEID_14_15,MEDICARE_DEID_16_16, MEDICARE_DEID_17_17, MEDICARE_DEID_18_20 | V_MBSF_ABCD_SUMMARY_DEID | COVSTART, BENE_DOB | you can calculate age at COVSTART to see if it was under 65 yo |
| MEDICARE_DEID_14_15,MEDICARE_DEID_16_16, MEDICARE_DEID_17_17, MEDICARE_DEID_18_20 | V_MBSF_ABCD_SUMMARY_DEID | OREC | https://resdac.org/cms-data/variables/original-reason-entitlement-code |
 
![Blank diagram - Page 4](https://github.com/gpcnetwork/cdc-als4m-mu/assets/19035729/fa2ffbc8-8069-4273-8d29-3aba27b225b6)

**Comment by Askarafshar** [comment]
Thanks for the info!

**Comment by Askarafshar** [comment]
**Analysis of ALS Patient Coverage Start Age and Entitlement Reasons** 

- **Patient Identification and Enrollment Period**:

Using ICD-9 and ICD-10 codes with a two-year wash-up period for enrollment, **4,600** patients were identified with ALS.

- **Age at Start of Coverage**:

With calculating the age at the start of coverage: **1,178** patients (**25.60%**) were below the age of 65, while **3,423** patients (**74.40%**) were aged 65 or above.

- **Coverage Entitlement Reasons**:

Looking into the reasons for coverage, categorized under the Original Reason for Entitlement Code (OREC):

- A vast majority of patients **above 65 years old**, amounting to **3,411** individuals (**99.65%**), are covered under **Old Age and Survivor’s Insurance (OASI)**.
- Only a small fraction, **12** patients (**0.35%**), in the same age group have **Disability Insurance Benefits (DIB)**.

- **For patients below 65**, 985 individuals (**83.62%**) receive coverage due to **Disability Insurance Benefits (DIB)**, with 164 patients (**13.92%**) under **Old Age and Survivor’s Insurance (OASI)**.
- A relatively small number of patients below 65 are covered for End-stage Renal Disease (ESRD) and concurrent DIB and ESRD, totaling 18 (1.53%) and 11 (0.93%) patients respectively.

**Comment by sxinger** [comment]
so, almost all of our cohort are late-onset cases, which would be something we can mention in the manuscript
